language: java
jdk:
  - oraclejdk8
deploy:
  provider: s3
  bucket: "retrospective-board"
  upload-dir: snapshot
  skip_cleanup: true
  local_dir: artifacts
  region: eu-central-1
script:
   - mvn install